# Site settings
title: Ilaria Colazzo
email: I.Colazzo@exeter.ac.uk
description: Postdoctoral research fellow
baseurl: ""
url: ""


# # Google analytics ID: Remove or use your own!
# google_analytics: UA-167467135-1
# google_analytics_4: G-02KDGRRB2T
# google_tag_manager: GTM-TZ9Z7HZ

# Footer info
affiliation: >
    Dr. Ilaria Colazzo<br/>
    <a href="https://www.exeter.ac.uk/" target="_blank">University of Exeter</a><br/>
    <a href="https://mathematics.exeter.ac.uk/">Department of Mathematics</a><br/>
    Exeter, UK

location: >
  College of Engineering, Mathematics and Physical Sciences, <br/>
  University of Exeter, Harrison Building, <br/>
  North Park Road, Exeter, EX4 4QF

contact: >
    <a href="mailto:I.Colazzo@exeter.ac.uk" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact me via email</a> <br/>

# Pages shown in navbar
nav_pages:
  - name: about
  - name: publications
  - name: talks
  # - name: research
  # - name: software
# - name: team
  - name: teaching


plugins: ['jekyll/scholar']

scholar:

  last_name: Colazzo
  first_name: [Ilaria]

  style: shb
  locale: en

  source: /cv/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

include:
  - .htaccess
  - _pages
  - Gemfile

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links


exclude:
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
